site_name: Document Intelligence

plugins:
  - glightbox
  
markdown_extensions:
  - attr_list
  - md_in_html


theme:
  name: "material"

nav:
  - Get Started: main.md
  - Document Ingelligence: index.md
  - Document Optical Character Recognition (OCR): document_ocr.md 
  - Document Pre-processing Methods: document_pre-processing_methods.md
  - Document Question Answering: document_question_answering.md
  - Extraction Methods - Information: table_extraction_information.md
  - Extraction Methods - Structure: table_extraction_structure.md
  - Reference: reference.md